### ISSUE TITLE
[Question] Should the stack be running?

### ISSUE THREAD

**Issue by mietzen** [BretFisher/docker-vackup#12]
I haven't found anything regarding this, I was wondering if I should shutdown the stack before backing up. I was wondering if otherwise there could be corrupted data, e.g. in databases.

**Comment by BretFisher** [comment]
This is just standard Linux file copy, so that depends on what data you're copying.  Open files may get corrupted. With databases, you *always* use their backup tool first, and then you could copy those files out with vackup.
